name: Deploy iTravho Site

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./site  # Directory where Site is built
